version: "3.8"
services:
    frontend:
      image: aliahmed312/frontend-app
      container_name: frontend-service
      ports:
        - "8000:80"
      networks:
        - myNetwork

    backend:
      image: aliahmed312/backend-app
      container_name: backend-service
      ports:
        - "3000:3000"
      networks:
        - myNetwork
      depends_on:
        - db


    db:
       image: mysql:8.0-debian
       container_name: mysql-service
       environment:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: angular
       ports:
          - "3306:3306"
       networks:
          - myNetwork
       volumes:
          - database:/var/lib/mysql
       restart: always

volumes:
    database:

networks:
    myNetwork:
       driver: bridge



